#!/bin/sh

make -f make_test_strcasecmp_s  clean  
make -f make_test_strcasestr_s  clean  
make -f make_test_strcat_s  clean  
make -f make_test_strcmp_s  clean  
make -f make_test_strcmpfld_s  clean  
make -f make_test_strcpy_s  clean  
make -f make_test_strcpyfld_s  clean  
make -f make_test_strcpyfldin_s  clean  
make -f make_test_strcpyfldout_s  clean  
make -f make_test_strcspn_s  clean  
make -f make_test_strfirstchar_s  clean  
make -f make_test_strfirstdiff_s  clean  
make -f make_test_strfirstsame_s  clean  
make -f make_test_strisalphanumeric_s  clean  
make -f make_test_strisascii_s  clean  
make -f make_test_strisdigit_s  clean  
make -f make_test_strishex_s  clean  
make -f make_test_strislowercase_s  clean  
make -f make_test_strismixed_s  clean  
make -f make_test_strispassword_s  clean  
make -f make_test_strisuppercase_s  clean  
make -f make_test_strlastchar_s  clean  
make -f make_test_strlastdiff_s  clean  
make -f make_test_strlastsame_s  clean  
make -f make_test_strljustify_s  clean  
make -f make_test_strncat_s  clean  
make -f make_test_strncpy_s  clean  
make -f make_test_strnlen_s  clean  
make -f make_test_strnterminate_s  clean  
make -f make_test_strpbrk_s  clean  
make -f make_test_strprefix_s  clean  
make -f make_test_strremovews_s  clean  
make -f make_test_strspn_s  clean  
make -f make_test_strstr_s  clean  
make -f make_test_strtok_s  clean  
make -f make_test_strtolowercase_s  clean  
make -f make_test_strtouppercase_s  clean  
make -f make_test_strzero_s  clean  


