version: 3.0.{build}
max_jobs: 4
environment:
  matrix:
    - MINGW: 1
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      PLATFORM: x64
    - MINGW: 1
      MSYS2_ARCH: i686
      MSYSTEM: MINGW32
      PLATFORM: x86
    - CYGWIN: 1
      PLATFORM: x86
    - CYGWIN: 1
      PLATFORM: x64
matrix:
  allow_failures:
    - MINGW: 1
clone_depth: 1
#branches:
#  only:
#    - master
#    - /^smoke/
#    - /^maint-/
#    - /^win/

init:
  - git config --global core.autocrlf input
  # Disable popups as they hang the build as there is nobody to click on the OK button...
  # Hanging the build is a lot less user friendly than reporting a build failure.
  #
  # Disable of system hard error popup
  # See: https://msdn.microsoft.com/en-us/library/bb513638%28VS.85%29.aspx
  - reg add "HKLM\SYSTEM\CurrentControlSet\Control\Windows" /f /v ErrorMode /d 2
  # Disable the following popup on program failure:
  #     |       ** <program name> has stopped working **        |
  #     | Windows can check online for a solution to the problem|
  #     |  - Check online for a solution and close the program  |
  #     |  - Close the program                                  |
  # See: https://msdn.microsoft.com/en-us/library/bb513638%28VS.85%29.aspx
  - reg add "HKLM\Software\Microsoft\Windows\Windows Error Reporting" /f /v DontShowUI /d 1  
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # git bash conflicts with MinGW makefiles, esp. the space in 'Program Files'
  - set "PATH=%PATH:C:\Program Files\Git\usr\bin;=%"
  - if "%MINGW%"=="1" set PROCESSOR_ARCHITECTURE=%PLATFORM%
  - if "%PLATFORM%"=="x64" set PROCESSOR_ARCHITECTURE=AMD64
  - set P=
  - if "%PLATFORM%"=="x64" set P=64
  - if "%CYGWIN%"=="1" set CYGR=c:\cygwin%P%
  # mingw32 fails needing automake 3.69

build_script:
  #- if "%MINGW%"=="1" set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%;
  - if "%CYGWIN%"=="1" set PATH=%CYGR%\bin;c:\Windows\system32;c:\Windows;c:\Windows\system32\Wbem
  - if "%MINGW%"=="1" call build-tools\msys2.bat
  - bash -c "build-tools/autogen.sh"
  - bash -c "./configure -enable-unsafe --enable-norm-compat"
  - bash -c "make"

test_script:
  - bash -c "make check || (cat tests/test-suite.log; false)"
