# Build configuration for https://cirrus-ci.org
# Images at https://cirrus-ci.org/guide/FreeBSD/

freebsd_instance:
  image_family: freebsd-14-3
  cpu: 4
task:
  install_script:
    - pkg install -y autoconf automake libtool pkgconf git wget m4 gmake
  build_script:
    - build-aux/autogen.sh
    - CFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib MAKE=gmake ./configure --enable-unsafe --enable-norm-compat --disable-dependency-tracking
    - gmake
  test_script:
    - gmake check-log
