# Build configuration for https://cirrus-ci.org

freebsd_instance:
  image_family: freebsd-13-0
  cpu: 4
task:
  install_script:
    - pkg install -y autoconf automake libtool pkgconf git wget m4 gmake
  build_script:
    - build-aux/autogen.sh
    - CFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib ./configure --enable-unsafe --enable-norm-compat
    - gmake
  test_script:
    - gmake check-log
    - gmake distcheck
