#!/bin/sh

make -f make_perf_memcpy32_s   
make -f make_perf_memcpy_s   
make -f make_test_memcmp16_s   
make -f make_test_memcmp32_s   
make -f make_test_memcmp_s   
make -f make_test_memcpy16_s   
make -f make_test_memcpy32_s   
make -f make_test_memcpy_s   
make -f make_test_memmove16_s   
make -f make_test_memmove32_s   
make -f make_test_memmove_s   
make -f make_test_memset16_s   
make -f make_test_memset32_s   
make -f make_test_memset_s   
make -f make_test_memzero16_s   
make -f make_test_memzero32_s   
make -f make_test_memzero_s   


