#!/bin/sh

./p_memcpy32_s   
./p_memcpy_s   

./t_memcmp16_s   
./t_memcmp32_s   
./t_memcmp_s   
./t_memcpy16_s   
./t_memcpy32_s   
./t_memcpy_s   
./t_memmove16_s   
./t_memmove32_s   
./t_memmove_s   
./t_memset16_s   
./t_memset32_s   
./t_memset_s   
./t_memzero16_s   
./t_memzero32_s   
./t_memzero_s   


