#!/bin/bash
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# clang-format: a tool to run clang-format on files, one file at a time.
# Used as the pre-commit `clang-format` hook's entry point (unlike
# build-aux/clang-format-all.sh, which reformats the whole tree).
#
# Adapted from rcc's clang-format.sh.
#
# Copyright (C) 2016 Evan Klitzke <evan@eklitzke.org>
# Copyright (C) 2019 Reini Urban <rurban@cpan.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function usage {
	echo "Usage: $0 FILE..."
	exit 1
}

if [ $# -eq 0 ]; then
	usage
fi

# Variable that will hold the name of the clang-format command
FMT=""

# Some distros just call it clang-format. Others (e.g. Ubuntu) are insistent
# that the version number be part of the command. We prefer the bare
# clang-format first (picks up the pre-commit-installed binary when running
# via pre-commit), then fall back to versioned and macports variants.
for clangfmt in clang-format clang-format{-mp,}{-devel,-{22,21,20,19,18,15,8,7,6,5,4,3}{,.9,.8,.7,.6,.5,.4,.3,.2,.1,.0},}; do
	if which "$clangfmt" &>/dev/null; then
		FMT="$clangfmt"
		break
	fi
done

# Check if we found a working clang-format
if [ -z "$FMT" ]; then
	echo "failed to find clang-format"
	exit 1
fi

# Check all of the arguments first to make sure they're all files
for file in "$@"; do
	if [ "$file" = "-style=file" ]; then
		continue
	fi
	if [ ! -e "${file}" ]; then
		echo "${file} not found"
		usage
	fi
done

# Find a dominating file, starting from a given directory and going up.
find-dominating-file() {
	if [ -r "$1"/"$2" ]; then
		return 0
	fi
	if [ "$1" = "/" ]; then
		return 1
	fi
	find-dominating-file "$(realpath "$1"/..)" "$2"
	return $?
}

# Run clang-format -i on all of the things
for file in "$@"; do
	if [ "$file" = "-style=file" ]; then
		continue
	fi
	# Machine-generated files marked "DO NOT EDIT THIS FILE": never
	# reformat them here, regardless of their current formatting state.
	# mknorm.pl's own output (src/extwchar/unw*.h, src/extu8/un8if*.h)
	# already runs through clang-format at generation time (see
	# mknorm.pl's format_file()), so this is normally a no-op safety
	# net for it; src/extwchar/hangul.h and towctrans.c come from other
	# (external, not safeclib-owned) generators and are not formatted
	# at generation time, so this is load-bearing for those two.
	if grep -q 'DO NOT EDIT THIS FILE' "$file" 2>/dev/null; then
		echo "skip generated $file"
		continue
	fi
	# tests/test_*.c files with nested EXPECT_BOS(...) calls are hand-
	# aligned for readability; clang-format mangles the nesting. Same
	# exemption build-aux/clang-format-all.sh applies via .format-ignore.
	case "$file" in
	tests/test_*.c)
		if grep -q ' EXPECT_BOS.* EXPECT_BOS' "$file" 2>/dev/null; then
			echo "skip hand-aligned $file"
			continue
		fi
		;;
	esac
	dir="$(dirname "$file")"
	if ! find-dominating-file "$dir" .clang-format; then
		echo "Failed to find dominating .clang-format starting at $PWD"
		continue
	fi
	if ! ${FMT} --dry-run --Werror "$file" 2>/dev/null; then
		echo "  Formatted $file"
		${FMT} -i "$file"
		# clang-format mis-parses *_DIAG_IGNORE(-Wfoo-bar) as
		# arithmetic (-Wfoo MINUS bar) and inserts spaces around
		# every embedded hyphen, breaking the macro argument; undo
		# it. Scoped to lines with "DIAG_IGNORE(-W" so it can't
		# touch an unrelated "a - b". Same post-fixup as
		# build-aux/clang-format-all.sh; keep both in sync.
		if grep -q 'DIAG_IGNORE(-W' "$file" 2>/dev/null; then
			sed -i -E '/DIAG_IGNORE\(-W/ s/ - /-/g' "$file"
		fi
	fi
done
