/*------------------------------------------------------------------
 * towfc_s.c
 *
 * September 2017, Reini Urban
 * January 2022, Reini Urban
 * September 2026, Reini Urban
 *
 * Copyright (c) 2017,2022,2026 by Reini Urban
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *------------------------------------------------------------------
 */

#ifdef FOR_DOXYGEN
#include "safe_str_lib.h"
#else
#include "safeclib_private.h"
#include <ctype.h>
#include <wctype.h>
#endif

/**
 * @brief
 *    \b iswfc() checks the uppercase character for a mapping to foldcase,
 *    returning the number of new wide character codepoints needed.
 *    The usual \c iswupper(wc) case returns 1, and the special 104 full
 *    folding cases as specified in Unicode 10.0 \c CaseFolding.txt return either
 *    2 or 3. This implements Unicode 14.0. (5 errors for Unicode 15)
 *
 * @param[in]   wc  unicode character codepoint
 *
 * @retval  0   when there is no corresponding lowercase mapping.
 * @retval  1   when there is a corresponding common or simple foldcase
 *              mapping.
 * @retval  2   a full case-folding expands to 2 characters
 * @retval  3   a full case-folding expands to 3 characters
 *
 * @see
 *    towfc_s(), wcsfc_s(), towupper()
 */

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
#define RESTRICT restrict
#elif defined(__GNUC__)
#define RESTRICT __restrict__
#else
#define RESTRICT
#endif

/* Note: tables and code generated by perl Unicode::Towctrans. Do not mess with them. */

/* Unicode 18.0.0 has 233 code points for which the fold case mapping is not to
 * itself, or to tolower(), 128 of it return length 1, the rest 105 map to 2 or
 * 3 and are handled below.
 */

static const struct {
    unsigned short upper;
    unsigned short lower1;
    unsigned short lower2;
} tbl2[] = {
    // clang-format off
    {0x00DF, 0x0073, 0x0073}, /* LATIN SMALL LETTER SHARP S */
    {0x0130, 0x0069, 0x0307}, /* LATIN CAPITAL LETTER I WITH DOT ABOVE */
    {0x0149, 0x02BC, 0x006E}, /* LATIN SMALL LETTER N PRECEDED BY APOSTROPHE */
    {0x01F0, 0x006A, 0x030C}, /* LATIN SMALL LETTER J WITH CARON */
    {0x0587, 0x0565, 0x0582}, /* ARMENIAN SMALL LIGATURE ECH YIWN */
    {0x1E96, 0x0068, 0x0331}, /* LATIN SMALL LETTER H WITH LINE BELOW */
    {0x1E97, 0x0074, 0x0308}, /* LATIN SMALL LETTER T WITH DIAERESIS */
    {0x1E98, 0x0077, 0x030A}, /* LATIN SMALL LETTER W WITH RING ABOVE */
    {0x1E99, 0x0079, 0x030A}, /* LATIN SMALL LETTER Y WITH RING ABOVE */
    {0x1E9A, 0x0061, 0x02BE}, /* LATIN SMALL LETTER A WITH RIGHT HALF RING */
    {0x1E9E, 0x0073, 0x0073}, /* LATIN CAPITAL LETTER SHARP S */
    {0x1F50, 0x03C5, 0x0313}, /* GREEK SMALL LETTER UPSILON WITH PSILI */
    {0x1F80, 0x1F00, 0x03B9}, /* GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI */
    {0x1F81, 0x1F01, 0x03B9}, /* GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI */
    {0x1F82, 0x1F02, 0x03B9}, /* GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI */
    {0x1F83, 0x1F03, 0x03B9}, /* GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI */
    {0x1F84, 0x1F04, 0x03B9}, /* GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI */
    {0x1F85, 0x1F05, 0x03B9}, /* GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI */
    {0x1F86, 0x1F06, 0x03B9}, /* GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI */
    {0x1F87, 0x1F07, 0x03B9}, /* GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI */
    {0x1F88, 0x1F00, 0x03B9}, /* GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI */
    {0x1F89, 0x1F01, 0x03B9}, /* GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI */
    {0x1F8A, 0x1F02, 0x03B9}, /* GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI */
    {0x1F8B, 0x1F03, 0x03B9}, /* GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI */
    {0x1F8C, 0x1F04, 0x03B9}, /* GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI */
    {0x1F8D, 0x1F05, 0x03B9}, /* GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI */
    {0x1F8E, 0x1F06, 0x03B9}, /* GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI */
    {0x1F8F, 0x1F07, 0x03B9}, /* GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI */
    {0x1F90, 0x1F20, 0x03B9}, /* GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI */
    {0x1F91, 0x1F21, 0x03B9}, /* GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI */
    {0x1F92, 0x1F22, 0x03B9}, /* GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI */
    {0x1F93, 0x1F23, 0x03B9}, /* GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI */
    {0x1F94, 0x1F24, 0x03B9}, /* GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI */
    {0x1F95, 0x1F25, 0x03B9}, /* GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI */
    {0x1F96, 0x1F26, 0x03B9}, /* GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI */
    {0x1F97, 0x1F27, 0x03B9}, /* GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI */
    {0x1F98, 0x1F20, 0x03B9}, /* GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI */
    {0x1F99, 0x1F21, 0x03B9}, /* GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI */
    {0x1F9A, 0x1F22, 0x03B9}, /* GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI */
    {0x1F9B, 0x1F23, 0x03B9}, /* GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI */
    {0x1F9C, 0x1F24, 0x03B9}, /* GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI */
    {0x1F9D, 0x1F25, 0x03B9}, /* GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI */
    {0x1F9E, 0x1F26, 0x03B9}, /* GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI */
    {0x1F9F, 0x1F27, 0x03B9}, /* GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI */
    {0x1FA0, 0x1F60, 0x03B9}, /* GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI */
    {0x1FA1, 0x1F61, 0x03B9}, /* GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI */
    {0x1FA2, 0x1F62, 0x03B9}, /* GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI */
    {0x1FA3, 0x1F63, 0x03B9}, /* GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI */
    {0x1FA4, 0x1F64, 0x03B9}, /* GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI */
    {0x1FA5, 0x1F65, 0x03B9}, /* GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI */
    {0x1FA6, 0x1F66, 0x03B9}, /* GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI */
    {0x1FA7, 0x1F67, 0x03B9}, /* GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI */
    {0x1FA8, 0x1F60, 0x03B9}, /* GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI */
    {0x1FA9, 0x1F61, 0x03B9}, /* GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI */
    {0x1FAA, 0x1F62, 0x03B9}, /* GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI */
    {0x1FAB, 0x1F63, 0x03B9}, /* GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI */
    {0x1FAC, 0x1F64, 0x03B9}, /* GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI */
    {0x1FAD, 0x1F65, 0x03B9}, /* GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI */
    {0x1FAE, 0x1F66, 0x03B9}, /* GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI */
    {0x1FAF, 0x1F67, 0x03B9}, /* GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI */
    {0x1FB2, 0x1F70, 0x03B9}, /* GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI */
    {0x1FB3, 0x03B1, 0x03B9}, /* GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI */
    {0x1FB4, 0x03AC, 0x03B9}, /* GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI */
    {0x1FB6, 0x03B1, 0x0342}, /* GREEK SMALL LETTER ALPHA WITH PERISPOMENI */
    {0x1FBC, 0x03B1, 0x03B9}, /* GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI */
    {0x1FC2, 0x1F74, 0x03B9}, /* GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI */
    {0x1FC3, 0x03B7, 0x03B9}, /* GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI */
    {0x1FC4, 0x03AE, 0x03B9}, /* GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI */
    {0x1FC6, 0x03B7, 0x0342}, /* GREEK SMALL LETTER ETA WITH PERISPOMENI */
    {0x1FCC, 0x03B7, 0x03B9}, /* GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI */
    {0x1FD6, 0x03B9, 0x0342}, /* GREEK SMALL LETTER IOTA WITH PERISPOMENI */
    {0x1FE4, 0x03C1, 0x0313}, /* GREEK SMALL LETTER RHO WITH PSILI */
    {0x1FE6, 0x03C5, 0x0342}, /* GREEK SMALL LETTER UPSILON WITH PERISPOMENI */
    {0x1FF2, 0x1F7C, 0x03B9}, /* GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI */
    {0x1FF3, 0x03C9, 0x03B9}, /* GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI */
    {0x1FF4, 0x03CE, 0x03B9}, /* GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI */
    {0x1FF6, 0x03C9, 0x0342}, /* GREEK SMALL LETTER OMEGA WITH PERISPOMENI */
    {0x1FFC, 0x03C9, 0x03B9}, /* GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI */
    {0xFB00, 0x0066, 0x0066}, /* LATIN SMALL LIGATURE FF */
    {0xFB01, 0x0066, 0x0069}, /* LATIN SMALL LIGATURE FI */
    {0xFB02, 0x0066, 0x006C}, /* LATIN SMALL LIGATURE FL */
    {0xFB05, 0x0073, 0x0074}, /* LATIN SMALL LIGATURE LONG S T */
    {0xFB06, 0x0073, 0x0074}, /* LATIN SMALL LIGATURE ST */
    {0xFB13, 0x0574, 0x0576}, /* ARMENIAN SMALL LIGATURE MEN NOW */
    {0xFB14, 0x0574, 0x0565}, /* ARMENIAN SMALL LIGATURE MEN ECH */
    {0xFB15, 0x0574, 0x056B}, /* ARMENIAN SMALL LIGATURE MEN INI */
    {0xFB16, 0x057E, 0x0576}, /* ARMENIAN SMALL LIGATURE VEW NOW */
    {0xFB17, 0x0574, 0x056D}, /* ARMENIAN SMALL LIGATURE MEN XEH */
    {0, 0, 0}
    // clang-format on
};

static const struct {
    unsigned short upper;
    unsigned short lower1;
    unsigned short lower2;
    unsigned short lower3;
} tbl3[] = {
    // clang-format off
    {0x0390, 0x03B9, 0x0308, 0x0301}, /* GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS */
    {0x03B0, 0x03C5, 0x0308, 0x0301}, /* GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS */
    {0x1F52, 0x03C5, 0x0313, 0x0300}, /* GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA */
    {0x1F54, 0x03C5, 0x0313, 0x0301}, /* GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA */
    {0x1F56, 0x03C5, 0x0313, 0x0342}, /* GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI */
    {0x1FB7, 0x03B1, 0x0342, 0x03B9}, /* GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI */
    {0x1FC7, 0x03B7, 0x0342, 0x03B9}, /* GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI */
    {0x1FD2, 0x03B9, 0x0308, 0x0300}, /* GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA */
    {0x1FD3, 0x03B9, 0x0308, 0x0301}, /* GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA */
    {0x1FD7, 0x03B9, 0x0308, 0x0342}, /* GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI */
    {0x1FE2, 0x03C5, 0x0308, 0x0300}, /* GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA */
    {0x1FE3, 0x03C5, 0x0308, 0x0301}, /* GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA */
    {0x1FE7, 0x03C5, 0x0308, 0x0342}, /* GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI */
    {0x1FF7, 0x03C9, 0x0342, 0x03B9}, /* GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI */
    {0xFB03, 0x0066, 0x0066, 0x0069}, /* LATIN SMALL LIGATURE FFI */
    {0xFB04, 0x0066, 0x0066, 0x006C}, /* LATIN SMALL LIGATURE FFL */
    {0, 0, 0, 0}
    // clang-format on
};

/* Return the number of wide lower-case characters needed to full fold-case
   the given uppercase character. Returns 0, 1, 2 or 3.
   0 if the character stays the same, 1 if one character changes,
   2 or 3 if the character will be replaced with 2 or 3.

   Note that accents expand to more characters than 1 via NFD decomposition.
   iswfc only matches towfc_s, but not wcsfc_s which does NFD decomposition
   also.
*/
int iswfc(const uint32_t wc) {
    int i;
    for (i = 0; tbl2[i].upper; i++) {
        if (tbl2[i].upper == wc)
            return 2;
        if (tbl2[i].upper > wc)
            break;
    }
    for (i = 0; tbl3[i].upper; i++) {
        if (tbl3[i].upper == wc)
            return 3;
        if (tbl3[i].upper > wc)
            break;
    }
    if (wc == 0x1DF95) /* LATIN SMALL LIGATURE LONG S WITH DESCENDER S,
                          upper > 0xFFFF, kept out of the 16-bit tbl2 */
        return 2;
    if (wc >= 0x13A0 && wc <= 0x13F5) /* Cherokee upper syllables fold to
                                         themselves, CaseFolding.txt stability
                                         exception */
        return 0;
#if SIZEOF_WCHAR_T > 2
    return iswupper(wc) ? 1 : 0;
#else
    if (wc > 0xffff) {
        uint32_t lc = _towcase(wc, 1);
        return (lc != wc) ? 1 : 0;
    }
    return iswupper((wint_t)wc) ? 1 : 0;
#endif
}

/* The 128 single fc chars where fc is different to lc.
   Must only be called when we know for sure that the length is 1!
   Returns 1 if fc is different to lc, else -1.
   May return 2 on sizeof(wchar_t)==2 if >0xffff, i.e. converted to surrogate
   pair
 */
int _towfc_single(wchar_t *RESTRICT dest, const uint32_t src) {
    /* fc exceptions: not towlower */
    dest[1] = L'\0';
    if (src < 0xb5)
        goto single;
    if (src >= 0xb5 && src <= 0x3f5) {
        switch (src) {
        case 0xb5:
            dest[0] = 0x3bc;
            return 1; /* lc=b5 */
        case 0x17f:
            dest[0] = 0x73;
            return 1; /* lc=17f */
        case 0x345:
            dest[0] = 0x3b9;
            return 1; /* lc=345 */
        case 0x3c2:
            dest[0] = 0x3c3;
            return 1; /* lc=3c2 */
        case 0x3d0:
            dest[0] = 0x3b2;
            return 1; /* lc=3d0 */
        case 0x3d1:
            dest[0] = 0x3b8;
            return 1; /* lc=3d1 */
        case 0x3d5:
            dest[0] = 0x3c6;
            return 1; /* lc=3d5 */
        case 0x3d6:
            dest[0] = 0x3c0;
            return 1; /* lc=3d6 */
        case 0x3f0:
            dest[0] = 0x3ba;
            return 1; /* lc=3f0 */
        case 0x3f1:
            dest[0] = 0x3c1;
            return 1; /* lc=3f1 */
        case 0x3f5:
            dest[0] = 0x3b5;
            return 1; /* lc=3f5 */
        default:
            break;
        }
        goto single;
    } else if (unlikely(src >= 0x13a0 && src <= 0x13f5)) {
        /* Cherokee upper syllables fold to themselves, not to the newer
           lowercase AB70-ABBF/13F8-13FD block, per the CaseFolding.txt
           stability rule (preserve case folding stability for the
           originally-encoded, caseless syllables). */
        dest[0] = (wchar_t)src;
        return -1;
    } else if (unlikely(src >= 0x13f8 && src <= 0x13fd)) {
        dest[0] = src - 8;
        return 1;
    } else if (unlikely(src >= 0x1c80 && src <= 0x1c88)) {
        switch (src) {
        case 0x1c80:
            dest[0] = 0x432;
            return 1; /* lc=1c80 */
        case 0x1c81:
            dest[0] = 0x434;
            return 1; /* lc=1c81 */
        case 0x1c82:
            dest[0] = 0x43e;
            return 1; /* lc=1c82 */
        case 0x1c83:
            dest[0] = 0x441;
            return 1; /* lc=1c83 */
        case 0x1c84:
            dest[0] = 0x442;
            return 1; /* lc=1c84 */
        case 0x1c85:
            dest[0] = 0x442;
            return 1; /* lc=1c85 */
        case 0x1c86:
            dest[0] = 0x44a;
            return 1; /* lc=1c86 */
        case 0x1c87:
            dest[0] = 0x463;
            return 1; /* lc=1c87 */
        case 0x1c88:
            dest[0] = 0xa64b;
            return 1; /* lc=1c88 */
        default:
            break;
        }
        goto single;
    } else if (unlikely(src >= 0x1e9b && src <= 0x1fbe)) {
        switch (src) {
        case 0x1e9b:
            dest[0] = 0x1e61;
            return 1; /* lc=1e9b */
        case 0x1fbe:
            dest[0] = 0x3b9;
            return 1; /* lc=1fbe */
        default:
            break;
        }
        goto single;
    } else if (unlikely(src >= 0xa7dd && src <= 0xa7e2)) {
        switch (src) {
        case 0xa7dd:
            dest[0] = 0x277;
            return 1; /* lc=a7dd */
        case 0xa7e2:
            dest[0] = 0x27c;
            return 1; /* lc=a7e2 */
        default:
            break;
        }
        goto single;
    } else if (unlikely(src >= 0xab6c && src <= 0xabbf)) {
        switch (src) {
        case 0xab6c:
            dest[0] = 0xab4b;
            return 1; /* lc=ab6c */
        case 0xab6d:
            dest[0] = 0xab4c;
            return 1; /* lc=ab6d */
        case 0xab70:
            dest[0] = 0x13a0;
            return 1; /* lc=ab70 */
        case 0xab71:
            dest[0] = 0x13a1;
            return 1; /* lc=ab71 */
        case 0xab72:
            dest[0] = 0x13a2;
            return 1; /* lc=ab72 */
        case 0xab73:
            dest[0] = 0x13a3;
            return 1; /* lc=ab73 */
        case 0xab74:
            dest[0] = 0x13a4;
            return 1; /* lc=ab74 */
        case 0xab75:
            dest[0] = 0x13a5;
            return 1; /* lc=ab75 */
        case 0xab76:
            dest[0] = 0x13a6;
            return 1; /* lc=ab76 */
        case 0xab77:
            dest[0] = 0x13a7;
            return 1; /* lc=ab77 */
        case 0xab78:
            dest[0] = 0x13a8;
            return 1; /* lc=ab78 */
        case 0xab79:
            dest[0] = 0x13a9;
            return 1; /* lc=ab79 */
        case 0xab7a:
            dest[0] = 0x13aa;
            return 1; /* lc=ab7a */
        case 0xab7b:
            dest[0] = 0x13ab;
            return 1; /* lc=ab7b */
        case 0xab7c:
            dest[0] = 0x13ac;
            return 1; /* lc=ab7c */
        case 0xab7d:
            dest[0] = 0x13ad;
            return 1; /* lc=ab7d */
        case 0xab7e:
            dest[0] = 0x13ae;
            return 1; /* lc=ab7e */
        case 0xab7f:
            dest[0] = 0x13af;
            return 1; /* lc=ab7f */
        case 0xab80:
            dest[0] = 0x13b0;
            return 1; /* lc=ab80 */
        case 0xab81:
            dest[0] = 0x13b1;
            return 1; /* lc=ab81 */
        case 0xab82:
            dest[0] = 0x13b2;
            return 1; /* lc=ab82 */
        case 0xab83:
            dest[0] = 0x13b3;
            return 1; /* lc=ab83 */
        case 0xab84:
            dest[0] = 0x13b4;
            return 1; /* lc=ab84 */
        case 0xab85:
            dest[0] = 0x13b5;
            return 1; /* lc=ab85 */
        case 0xab86:
            dest[0] = 0x13b6;
            return 1; /* lc=ab86 */
        case 0xab87:
            dest[0] = 0x13b7;
            return 1; /* lc=ab87 */
        case 0xab88:
            dest[0] = 0x13b8;
            return 1; /* lc=ab88 */
        case 0xab89:
            dest[0] = 0x13b9;
            return 1; /* lc=ab89 */
        case 0xab8a:
            dest[0] = 0x13ba;
            return 1; /* lc=ab8a */
        case 0xab8b:
            dest[0] = 0x13bb;
            return 1; /* lc=ab8b */
        case 0xab8c:
            dest[0] = 0x13bc;
            return 1; /* lc=ab8c */
        case 0xab8d:
            dest[0] = 0x13bd;
            return 1; /* lc=ab8d */
        case 0xab8e:
            dest[0] = 0x13be;
            return 1; /* lc=ab8e */
        case 0xab8f:
            dest[0] = 0x13bf;
            return 1; /* lc=ab8f */
        case 0xab90:
            dest[0] = 0x13c0;
            return 1; /* lc=ab90 */
        case 0xab91:
            dest[0] = 0x13c1;
            return 1; /* lc=ab91 */
        case 0xab92:
            dest[0] = 0x13c2;
            return 1; /* lc=ab92 */
        case 0xab93:
            dest[0] = 0x13c3;
            return 1; /* lc=ab93 */
        case 0xab94:
            dest[0] = 0x13c4;
            return 1; /* lc=ab94 */
        case 0xab95:
            dest[0] = 0x13c5;
            return 1; /* lc=ab95 */
        case 0xab96:
            dest[0] = 0x13c6;
            return 1; /* lc=ab96 */
        case 0xab97:
            dest[0] = 0x13c7;
            return 1; /* lc=ab97 */
        case 0xab98:
            dest[0] = 0x13c8;
            return 1; /* lc=ab98 */
        case 0xab99:
            dest[0] = 0x13c9;
            return 1; /* lc=ab99 */
        case 0xab9a:
            dest[0] = 0x13ca;
            return 1; /* lc=ab9a */
        case 0xab9b:
            dest[0] = 0x13cb;
            return 1; /* lc=ab9b */
        case 0xab9c:
            dest[0] = 0x13cc;
            return 1; /* lc=ab9c */
        case 0xab9d:
            dest[0] = 0x13cd;
            return 1; /* lc=ab9d */
        case 0xab9e:
            dest[0] = 0x13ce;
            return 1; /* lc=ab9e */
        case 0xab9f:
            dest[0] = 0x13cf;
            return 1; /* lc=ab9f */
        case 0xaba0:
            dest[0] = 0x13d0;
            return 1; /* lc=aba0 */
        case 0xaba1:
            dest[0] = 0x13d1;
            return 1; /* lc=aba1 */
        case 0xaba2:
            dest[0] = 0x13d2;
            return 1; /* lc=aba2 */
        case 0xaba3:
            dest[0] = 0x13d3;
            return 1; /* lc=aba3 */
        case 0xaba4:
            dest[0] = 0x13d4;
            return 1; /* lc=aba4 */
        case 0xaba5:
            dest[0] = 0x13d5;
            return 1; /* lc=aba5 */
        case 0xaba6:
            dest[0] = 0x13d6;
            return 1; /* lc=aba6 */
        case 0xaba7:
            dest[0] = 0x13d7;
            return 1; /* lc=aba7 */
        case 0xaba8:
            dest[0] = 0x13d8;
            return 1; /* lc=aba8 */
        case 0xaba9:
            dest[0] = 0x13d9;
            return 1; /* lc=aba9 */
        case 0xabaa:
            dest[0] = 0x13da;
            return 1; /* lc=abaa */
        case 0xabab:
            dest[0] = 0x13db;
            return 1; /* lc=abab */
        case 0xabac:
            dest[0] = 0x13dc;
            return 1; /* lc=abac */
        case 0xabad:
            dest[0] = 0x13dd;
            return 1; /* lc=abad */
        case 0xabae:
            dest[0] = 0x13de;
            return 1; /* lc=abae */
        case 0xabaf:
            dest[0] = 0x13df;
            return 1; /* lc=abaf */
        case 0xabb0:
            dest[0] = 0x13e0;
            return 1; /* lc=abb0 */
        case 0xabb1:
            dest[0] = 0x13e1;
            return 1; /* lc=abb1 */
        case 0xabb2:
            dest[0] = 0x13e2;
            return 1; /* lc=abb2 */
        case 0xabb3:
            dest[0] = 0x13e3;
            return 1; /* lc=abb3 */
        case 0xabb4:
            dest[0] = 0x13e4;
            return 1; /* lc=abb4 */
        case 0xabb5:
            dest[0] = 0x13e5;
            return 1; /* lc=abb5 */
        case 0xabb6:
            dest[0] = 0x13e6;
            return 1; /* lc=abb6 */
        case 0xabb7:
            dest[0] = 0x13e7;
            return 1; /* lc=abb7 */
        case 0xabb8:
            dest[0] = 0x13e8;
            return 1; /* lc=abb8 */
        case 0xabb9:
            dest[0] = 0x13e9;
            return 1; /* lc=abb9 */
        case 0xabba:
            dest[0] = 0x13ea;
            return 1; /* lc=abba */
        case 0xabbb:
            dest[0] = 0x13eb;
            return 1; /* lc=abbb */
        case 0xabbc:
            dest[0] = 0x13ec;
            return 1; /* lc=abbc */
        case 0xabbd:
            dest[0] = 0x13ed;
            return 1; /* lc=abbd */
        case 0xabbe:
            dest[0] = 0x13ee;
            return 1; /* lc=abbe */
        case 0xabbf:
            dest[0] = 0x13ef;
            return 1; /* lc=abbf */
        default:
            break;
        }
        goto single;
    } else if (unlikely(src >= 0x1df40 && src <= 0x1df7e)) {
        switch (src) {
        case 0x1df40:
            dest[0] = 0x1df41;
            return 1; /* lc=1df40 */
        case 0x1df48:
            dest[0] = 0x1df49;
            return 1; /* lc=1df48 */
        case 0x1df4a:
            dest[0] = 0x1df4b;
            return 1; /* lc=1df4a */
        case 0x1df4d:
            dest[0] = 0x1df4e;
            return 1; /* lc=1df4d */
        case 0x1df51:
            dest[0] = 0x1df52;
            return 1; /* lc=1df51 */
        case 0x1df68:
            dest[0] = 0x1df69;
            return 1; /* lc=1df68 */
        case 0x1df6a:
            dest[0] = 0x1df6b;
            return 1; /* lc=1df6a */
        case 0x1df6c:
            dest[0] = 0x1df6d;
            return 1; /* lc=1df6c */
        case 0x1df6e:
            dest[0] = 0x1df6f;
            return 1; /* lc=1df6e */
        case 0x1df72:
            dest[0] = 0x1df73;
            return 1; /* lc=1df72 */
        case 0x1df74:
            dest[0] = 0x1df75;
            return 1; /* lc=1df74 */
        case 0x1df76:
            dest[0] = 0x1df77;
            return 1; /* lc=1df76 */
        case 0x1df78:
            dest[0] = 0x1df79;
            return 1; /* lc=1df78 */
        case 0x1df7a:
            dest[0] = 0x1df7b;
            return 1; /* lc=1df7a */
        case 0x1df7c:
            dest[0] = 0x1df7d;
            return 1; /* lc=1df7c */
        case 0x1df7e:
            dest[0] = 0x1df7f;
            return 1; /* lc=1df7e */
        default:
            break;
        }
        goto single;
    }

single:
#if SIZEOF_WCHAR_T > 2
    dest[0] = src < 128 ? (wchar_t)tolower(src) : (wchar_t)_towcase(src, 1);
    return (uint32_t)dest[0] == src ? -1 : 1;
#else
{
    uint32_t cp = src < 128 ? (uint32_t)tolower(src) : _towcase(src, 1);
    if (unlikely(cp > 0xffff)) {
        dest[0] = 0xd800 + (((cp - 0x10000) >> 10) & 0x3ff);
        dest[1] = 0xdc00 + (cp & 0x3ff);
        dest[2] = 0;
        return cp == src ? -1 : 2;
    } else {
        dest[0] = cp;
        return cp == src ? -1 : 1;
    }
}
#endif
}

/**
 * @def towfc_s(dest,dmax,src)
 * @brief
 *    \c towfc_s() converts a wide character to fully fold-cased (lowercased
 *    with possible expansions), according to the Unicode 10.0 CaseFolding
 *    table. Even in most the unsuccessul cases, just not with with ESNULLP
 *    and ESZEROL dest is being written to.
 *
 *  @details
 *    As of Unicode 10.0 there are no possible results as surrogate pairs with
 *    \c sizeof(wchar_t)==2, all results are below U+10000.
 *
 * @param[out]  dest  wide string buffer to store result
 * @param[in]   dmax  maximum size of dest, should be 4. (3 + NULL)
 * @param[in]   src   wide character to convert to lowercase
 *
 * @pre  dest shall not be a null pointer.
 * @pre  dmax shall be bigger than 3.
 * @pre  dmax shall not be greater than RSIZE_MAX_WSTR and size of dest.
 *
 * @retval  >=0          on successful operation, returns the number
 *                       of converted wide characters: 0-3. Or <0 on errors.
 * @retval  -ESNULLP     when dest is NULL pointer
 * @retval  -ESZEROL     when dmax = 0
 * @retval  -ESLEMIN     when dmax < 4
 * @retval  -ESLEMAX     when dmax > RSIZE_MAX_WSTR
 * @retval  -EOVERFLOW   when dmax > size of dest (optionally, when the
 * compiler knows the object_size statically)
 * @retval  -ESLEWRNG    when dmax != size of dest and --enable-error-dmax
 * @retval  -ESNOTFND    when no mapping for src was found, iswfc is wrong.
 *
 * @see
 *    iswfc(), wcsfc_s(), towlower()
 */

/* Writes the fold-cased wide string to dest from the given uppercase wide
   character. dmax should be 4 (3 wchar's + \0).
   Returns the number of replaced wide characters, or -ESNOTFND if not
   replaced.
*/
#ifdef FOR_DOXYGEN
int towfc_s(wchar_t *restrict dest, rsize_t dmax, const uint32_t src)
#else
EXPORT int _towfc_s_chk(wchar_t *restrict dest, rsize_t dmax, const uint32_t src,
                        const size_t destbos)
#endif
{
    int i;
    const size_t destsz = dmax * sizeof(wchar_t);

    if (unlikely(dest == NULL)) {
        invoke_safe_str_constraint_handler("towfc_s: "
                                           "dest is null",
                                           NULL, ESNULLP);
        return -(ESNULLP);
    }
    if (unlikely(dmax < 4)) {
        invoke_safe_str_constraint_handler("towfc_s: "
                                           "dmax is < 4",
                                           (void *)dest, ESLEMIN);
        return -(ESLEMIN);
    }
    dest[0] = L'\0';
    if (unlikely(dmax > RSIZE_MAX_WSTR)) {
        invoke_safe_str_constraint_handler("towfc_s: "
                                           "dmax exceeds max",
                                           (void *)dest, ESLEMAX);
        return -(ESLEMAX);
    }
    if (destbos == BOS_UNKNOWN) {
        BND_CHK_PTR_BOUNDS(dest, destsz);
    } else {
        if (unlikely(destsz > destbos)) {
            invoke_safe_str_constraint_handler("towfc_s: dmax exceeds dest",
                                               (void *)dest, EOVERFLOW);
            return -(EOVERFLOW);
        }
#ifdef HAVE_WARN_DMAX
        if (unlikely(destsz != destbos)) {
            handle_str_bos_chk_warn("towfc_s", (char *)dest, dmax,
                                    destbos / sizeof(wchar_t));
#ifdef HAVE_ERROR_DMAX
            return (-ESLEWRNG);
#endif
        }
#endif
    }

    if (src < 128) {
        dest[1] = L'\0';
        dest[0] = tolower(src);
        return (uint32_t)dest[0] == src ? -(ESNOTFND) : 1;
    }

    for (i = 0; tbl2[i].upper; i++) {
        if (tbl2[i].upper == src) {
            dest[0] = tbl2[i].lower1;
            dest[1] = tbl2[i].lower2;
            dest[2] = L'\0';
            return 2;
        }
        if (tbl2[i].upper > src)
            break;
    }
    for (i = 0; tbl3[i].upper; i++) {
        if (tbl3[i].upper == src) {
            dest[0] = tbl3[i].lower1;
            dest[1] = tbl3[i].lower2;
            dest[2] = tbl3[i].lower3;
            dest[3] = L'\0';
            return 3;
        }
        if (tbl3[i].upper > src)
            break;
    }
    if (src == 0x1DF95) { /* LATIN SMALL LIGATURE LONG S WITH DESCENDER S,
                              upper > 0xFFFF, kept out of the 16-bit tbl2 */
        dest[0] = 0x0073;
        dest[1] = 0x0073;
        dest[2] = L'\0';
        return 2;
    }

    /* fc exceptions: not towlower, for c == 1 */
    return _towfc_single(dest, src);
}
