/* ex: set ro ft=c: -*- buffer-read-only: t -*-
 *
 * !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 * This file is auto-generated by Unicode-Normalize 1.27
 * mkheader -uni -ind -std
 * for Unicode 14.0.0 UTF-16
 * Any changes here will be lost!
 */
/* Composite exclusions */
bool isExclusion (uint32_t uv);

bool isExclusion (uint32_t uv)
{
  return
	(2392 <= uv && uv <= 2399)
	|| (2524 <= uv && uv <= 2525)
	|| uv == 2527
	|| uv == 2611
	|| uv == 2614
	|| (2649 <= uv && uv <= 2651)
	|| uv == 2654
	|| (2908 <= uv && uv <= 2909)
	|| uv == 3907
	|| uv == 3917
	|| uv == 3922
	|| uv == 3927
	|| uv == 3932
	|| uv == 3945
	|| uv == 3958
	|| uv == 3960
	|| uv == 3987
	|| uv == 3997
	|| uv == 4002
	|| uv == 4007
	|| uv == 4012
	|| uv == 4025
	|| uv == 10972
	|| uv == 64285
	|| uv == 64287
	|| (64298 <= uv && uv <= 64310)
	|| (64312 <= uv && uv <= 64316)
	|| uv == 64318
	|| (64320 <= uv && uv <= 64321)
	|| (64323 <= uv && uv <= 64324)
	|| (64326 <= uv && uv <= 64334)
	|| (119134 <= uv && uv <= 119140)
	|| (119227 <= uv && uv <= 119232)
	? 1 : 0;
}

/* Singletons */
bool isSingleton (uint32_t uv);

bool isSingleton (uint32_t uv)
{
  return
	(832 <= uv && uv <= 833)
	|| uv == 835
	|| uv == 884
	|| uv == 894
	|| uv == 903
	|| uv == 8049
	|| uv == 8051
	|| uv == 8053
	|| uv == 8055
	|| uv == 8057
	|| uv == 8059
	|| uv == 8061
	|| uv == 8123
	|| uv == 8126
	|| uv == 8137
	|| uv == 8139
	|| uv == 8147
	|| uv == 8155
	|| uv == 8163
	|| uv == 8171
	|| (8174 <= uv && uv <= 8175)
	|| uv == 8185
	|| uv == 8187
	|| uv == 8189
	|| (8192 <= uv && uv <= 8193)
	|| uv == 8486
	|| (8490 <= uv && uv <= 8491)
	|| (9001 <= uv && uv <= 9002)
	|| (63744 <= uv && uv <= 64013)
	|| uv == 64016
	|| uv == 64018
	|| (64021 <= uv && uv <= 64030)
	|| uv == 64032
	|| uv == 64034
	|| (64037 <= uv && uv <= 64038)
	|| (64042 <= uv && uv <= 64109)
	|| (64112 <= uv && uv <= 64217)
	|| (194560 <= uv && uv <= 195101)
	? 1 : 0;
}

/* non-starter decompositions */
bool isNonStDecomp (uint32_t uv);

bool isNonStDecomp (uint32_t uv)
{
  return
	uv == 836
	|| uv == 3955
	|| uv == 3957
	|| uv == 3969
	? 1 : 0;
}

/* may be composed with a prev char */
bool isComp2nd (uint32_t uv);

bool isComp2nd (uint32_t uv)
{
  return
	(768 <= uv && uv <= 772)
	|| (774 <= uv && uv <= 780)
	|| uv == 783
	|| uv == 785
	|| (787 <= uv && uv <= 788)
	|| uv == 795
	|| (803 <= uv && uv <= 808)
	|| (813 <= uv && uv <= 814)
	|| (816 <= uv && uv <= 817)
	|| uv == 824
	|| uv == 834
	|| uv == 837
	|| (1619 <= uv && uv <= 1621)
	|| uv == 2364
	|| uv == 2494
	|| uv == 2519
	|| uv == 2878
	|| (2902 <= uv && uv <= 2903)
	|| uv == 3006
	|| uv == 3031
	|| uv == 3158
	|| uv == 3266
	|| (3285 <= uv && uv <= 3286)
	|| uv == 3390
	|| uv == 3415
	|| uv == 3530
	|| uv == 3535
	|| uv == 3551
	|| uv == 4142
	|| (4449 <= uv && uv <= 4469)
	|| (4520 <= uv && uv <= 4546)
	|| uv == 6965
	|| (12441 <= uv && uv <= 12442)
	|| uv == 69818
	|| uv == 69927
	|| uv == 70462
	|| uv == 70487
	|| uv == 70832
	|| uv == 70842
	|| uv == 70845
	|| uv == 71087
	|| uv == 71984
	? 1 : 0;
}

